### ISSUE TITLE
1.10.2 todolist

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#241]
When i come back to ic2c which can be either never or very soon or very late. But as of right now its dead.
- [x] Miner deletes one mining pipe after completion #238 
- [x] WoodGas, Water, Lava Cells are not working because a lot of mods dropped old fluid container system. #237 
- [x] Chests should use OreDictionary for some other mods so it doesn't break classic #236 
- [x] Crafting the 8x hydrated charcoal recipe with a bucket turns it into an empty cell #234 
- [x] Ranged Pumps scanner fails for some reason #231 
- [x] Basic Steam Turbine Texture has a tiny Offset between on/off #227 
- [x] Add Russian Language #226 
- [x] Industrial Worktable doesn't drop the Memory Sticks when wrenched #233
